Avoid crashes on nodes without text
itkach/tei2slob pull request #5
Opened 2018-10-20 17:30 UTC by humenda

Missing information, such as the copyright holder, could lead to a
crash. An empty string is more appropriate.

2018-10-21 15:08 UTC, itkach requested changes
With the additional check the ternary conditional becomes hard to grok, it's better to rewrite it like so:
```python
if element is not None and element.text:
    return element.text
return ''
```
(Also, as a side note, avoid breaking up long lines with `\`, implicit line continuation within parenthesis is the preferred way, see https://www.python.org/dev/peps/pep-0008/)

2018-10-22 13:14 UTC, itkach commented on tei2slob/__init__.py
> +        return element
pretty sure you meant `element.text`

2018-10-22 16:47 UTC, humenda commented
>```python
>if element is not None and element.text:
Why `element is None` instead of `not element`?

>(Also, as a side note, avoid breaking up long lines with `\`, implicit line
>continuation within parenthesis is the preferred way
Interesting, thanks.

2018-10-23 12:08 UTC, itkach commented
> Why `element is None` instead of `not element`?

Because "falsiness" of an XML element is not well defined and ElementTree XML parser produces a warning for `not element`. See e.g. [here](https://stackoverflow.com/questions/18583162/difference-between-if-obj-and-if-obj-is-not-none) for more details

2018-10-23 12:10 UTC, merged